import Header from "@/components/Header";
// import "../studio/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="block overflow-auto bg-[#050505] text-white w-full h-full">
        <div className="flex flex-col w-full h-full">
          <Header />
          {children}
        </div>
      </div>
    </>
  );
}
