import Header from "@/components/Header";
// import "../studio/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className= {`${inter.className} bg-[#050505]`}>
        <div className=" bg-[#050505] text-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
