"use client";

import Header from "@/components/Header";
import SelectCommunityModal from "@/components/Modals/SelectCommunity";
import { store } from "@/store/store";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const communityId = store((state) => state.communityId);
  const path = usePathname();
  console.log(path);

  const selectedPaths = ["/studio/customize/new-community"];

  function onSelectedPaths(selectedPaths: string[], path: string) {
    return selectedPaths.includes(path);
  }

  return (
    <>
      <div className="block overflow-auto bg-[#050505] text-white w-full h-full">
        <div className="flex flex-col w-full h-full">
          <Header />
          {communityId ? (
            <>{children}</>
          ) : onSelectedPaths(selectedPaths, path) ? (
            <>{children}</>
          ) : (
            <SelectCommunityModal />
          )}
        </div>
      </div>
    </>
  );
}
