import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quiverbliss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${inter.className}flex flex-col bg-[#F2F6F9] w-full h-full overflow-x-hidden overscroll-none`} lang="en">
      <body className={"flex flex-col w-full h-full"}>{children}</body>
    </html>
  );
}
