import HeaderL from "@/components/HeaderL";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Avatar from "@/components/Avatar";
import Cover from "@/components/Cover";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F2F6F9]`}>
        <div className=" bg-[#F2F6F9] text-[#282B36]">
          <HeaderL />
          <div className=" flex flex-col gap-16">
            <div className=" ">
              <Cover src={"/banner.png" || ""} />
              <Avatar src={"/banner-logo.png" || ""} />
            </div>
            <Nav />
          </div>

          {children}
        </div>
      </body>
    </html>
  );
}
